### ISSUE TITLE
Error running programmatic usage

### ISSUE THREAD

**Issue by falcuma** [mobilcom-debitel/got-swag#3]
I've been testing and I can't find anything on the error I get, both using mocha and pure JS.

```
 
  1) My test suite "before all" hook:
     TypeError: Promise.all is not a function
      at Function.all (native)
      at bundleApis (c:\Users\gollivier\Desktop\loopHPC2\bikube\MESO_Bikube_Tools_verif\node_modules\got-swag\lib\bundle
Apis.js:13:18)
      at mocha (c:\Users\gollivier\Desktop\loopHPC2\bikube\MESO_Bikube_Tools_verif\node_modules\got-swag\lib\mocha.js:13
:10)
      at Context.<anonymous> (c:\Users\gollivier\Desktop\loopHPC2\bikube\MESO_Bikube_Tools_verif\node_modules\got-swag\l
ib\describe.js:8:5)
      at callFnAsync (c:\Users\gollivier\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:349:8)
      at Hook.Runnable.run (c:\Users\gollivier\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:301:7)
      at next (c:\Users\gollivier\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:298:10)
      at Immediate._onImmediate (c:\Users\gollivier\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:320:5)
```

And 

 ```
return Promise.all( apis.map( function ( api ) {
                           ^

TypeError: apis.map is not a function
    at bundleApis (c:\Users\gollivier\Desktop\loopHPC2\bikube\MESO_Bikube_Tools_verif\node_modules\got-swag\lib\bundleAp
is.js:13:28)
    at Object.test (c:\Users\gollivier\Desktop\loopHPC2\bikube\MESO_Bikube_Tools_verif\node_modules\got-swag\lib\test.js
:12:10)
    at Object.<anonymous> (c:\Users\gollivier\Desktop\loopHPC2\bikube\MESO_Bikube_Tools_verif\test\test.js:5:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

Any lights ?

**Comment by morris** [comment]
Hi @falcuma,

the first error indicates an older Node.js without ES6 Promises. Would you mind upgrading to v6? The second error should be gone as well.

Best

**Comment by morris** [comment]
I'm closing this for now as I'm pretty sure this is related to an unsupported version of Node.js. Feel free to reopen if the issue persists.

**Comment by plaguna** [comment]
```
node --version
v7.10.0
node app.js 
/../node_modules/got-swag/lib/bundleApis.js:13
  return Promise.all( apis.map( function ( api ) {
                           ^
TypeError: apis.map is not a function
    at bundleApis (/../node_modules/got-swag/lib/bundleApis.js:13:28)
    at Object.test (/../node_modules/got-swag/lib/test.js:12:10)
    at Object.<anonymous> (/../app.js:4:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
```

I am having the same problem. Running latest node installed from brew on macOS.
